# Generated by Django 5.2.4 on 2025-07-08 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='trabajadores_asignados',
            field=models.ManyToManyField(blank=True, related_name='trabajos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produccion',
            name='trabajo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajo'),
        ),
        migrations.AddField(
            model_name='fichacosto',
            name='trabajo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajo'),
        ),
        migrations.AddField(
            model_name='detallediseno',
            name='trabajo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_diseno', to='trabajos.trabajo'),
        ),
        migrations.AddField(
            model_name='archivodiseno',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_diseno', to='trabajos.trabajo'),
        ),
    ]
