# Generated by Django 5.2.4 on 2025-07-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ci',
            field=models.CharField(default=94050840123, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Mario', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('almacen', 'Almacenero'), ('comercial', 'Comercial'), ('diseñador', 'Diseñador'), ('tecnico', 'Técnico de producción'), ('economico', 'Económico')], max_length=20),
        ),
    ]
